# ----------------------------------------------------------
#
#               NOPE Anti-Cheat Configuration
#
#   This is the configuration for NOPE. I recommend keeping
#    the default values unless you know what you're doing.
#
# ----------------------------------------------------------

#               -------------------------------
#                     Global Configuration
#               -------------------------------

Global: true # If disabled, NOPE will be disabled
# Whether or not to teleport the player back when they're flagged
SetBack: false 
Scoreboard: true
Log: true
UpdateChecker:
  Enabled: true
  InGame: true

#               -------------------------------
#                     Banwave Configuration
#               -------------------------------

VlForInstaBan: 1500 # Minimum VL required for instant ban
VlForBanwave: 1000 # Minimum VL required to be queued for banwave
BanwaveRate: 36000 # Rate of banwave (in ticks)

#               -------------------------------
#                  Notification Configuration
#       Make sure staff members have nope.message.normal
#               -------------------------------

Minimum: 20 #Minimum VL to notify staff members
SecondsMinimum: 5000 #Cooldown of hack messages to prevent spam

# Each new color is a new level, this is based off percentage to VL for instant ban
# More colors = more notifications
VlColors: 
- '&a'
- '&e'
- '&6'
- '&c'
- '&4'

# If enabled, developer messages will be sent to the player and commands will not execute
DevMode: false 
DebugMode: false

CommandsForBan:
- kick %player% Hacking (%hack%) (%token%)
- say %player% was banned for %hack% (%token%)

CommandsForBanwave:
- kick %player% Hacking - Banwave (%hack%) (%token%)
- say %player% was banwaved for %hack% (%token%)

#               -------------------------------
#                     Check Configuration
#       Here you can configure which checks are/aren't enabled
#         You can also toggle these ingame with /nope stats
#   make sure to restart your server after modifying these settings
#               -------------------------------

Checks:
  Movement:
    Enabled: true
    Flight:
      Enabled: true
      Flight#1:
        Enabled: true
      Flight#2:
        Enabled: true
      Flight#3:
        Enabled: true
      Flight#4:
        Enabled: true
      Flight#5:
        Enabled: true
      Flight#6:
        Enabled: true
    Speed:
      Enabled: true
      Speed#1:
        Enabled: true
      Speed#2:
        Enabled: true
      Speed#3:
        Enabled: true
    ClonedMovements:
      Enabled: true
      ClonedMovement#1:
        Enabled: true
    Step:
      Enabled: true
      Step#1:
        Enabled: true
    FastClimb:
      Enabled: true
      FastClimb#1:
        Enabled: true
    Jesus:
      Enabled: true
      Jesus#1:
        Enabled: true
    FastSneak:
      Enabled: true
      FastSneak#1:
        Enabled: true
    NoWeb:
      Enabled: true
      NoWeb#1:
        Enabled: true
    AutoWalk:
      Enabled: true
      AutoWalk#1:
        Enabled: true
    AntiAFK:
      Enabled: true
      AntiAFK#1:
        Enabled: true
    InventoryMove:
      Enabled: true
      InventoryMove#1:
        Enabled: true
    AntiRotate:
      Enabled: true
      AntiRotate#1:
        Enabled: true
    NoSlowDown:
      Enabled: true
      NoSlowDown#1:
        Enabled: true
      NoSlowDown#2:
        Enabled: true
      NoSlowDown#3:
        Enabled: true
      NoSlowDown#4:
        Enabled: true
      NoSlowDown#5:
        Enabled: true
    SafeWalk:
      Enabled: true
      SafeWalk#1:
        Enabled: true
    Spider:
      Enabled: true
      Spider#1:
        Enabled: true
    Glide:
      Enabled: true
      Glide#1:
        Enabled: true
    BHop:
      Enabled: true
      BHop#1:
        Enabled: true
  Tick:
    Enabled: true
    Timer:
      Enabled: true
      Timer#1:
        Enabled: true
      Timer#2:
        Enabled: true
  Player:
    Enabled: true
    NoFall:
      Enabled: true
      NoFall#1:
        Enabled: true
    GhostHand:
      Enabled: true
      GhostHand#1:
        Enabled: true
    FastEat:
      Enabled: true
      FastEat#1:
        Enabled: true
    ChestStealer:
      Enabled: true
      ChestStealer#1:
        Enabled: true
    AntiFire:
      Enabled: true
      AntiFire#1:
        Enabled: true
    SelfHarm:
      Enabled: true
      SelfHarm#1:
        Enabled: true
    Zoot:
      Enabled: true
      Zoot#1:
        Enabled: true
    AutoTool:
      Enabled: true
      AutoTool#1:
        Enabled: true
  World:
    Enabled: true
    Scaffold:
      Enabled: true
      Scaffold#1:
        Enabled: true
      Scaffold#2:
        Enabled: true
      Scaffold#3:
        Enabled: true
    IllegalBlockBreak:
      Enabled: true
      IllegalBlockBreak#1:
        Enabled: true
    IllegalBlockPlace:
      Enabled: true
      IllegalBlockPlace#1:
        Enabled: true
    FastBreak:
      Enabled: true
      FastBreak#1:
        Enabled: true
  Combat:
    Enabled: true
    FastBow:
      Enabled: true
      FastBow#1:
        Enabled: true
    AutoClicker:
      Enabled: true
      AutoClicker#1:
        Enabled: true
    HighCPS:
      Enabled: true
      HighCPS#1:
        Enabled: true
      HighCPS#2:
        Enabled: true
      HighCPS#3:
        Enabled: true
    Reach:
      Enabled: true
      Reach#1:
        Enabled: true
    KillAura:
      Enabled: true
      KillAura#2:
        Enabled: true
      KillAura#5:
        Enabled: true
      KillAura#6:
        Enabled: true
      KillAura#7:
        Enabled: true
    AntiKB:
      Enabled: true
      AntiKB#1:
        Enabled: true
    AutoArmor:
      Enabled: true
      AutoArmor#1:
        Enabled: true
  Render:
    Enabled: true
    InvalidMovement:
      Enabled: true
      InvalidMovement#1:
        Enabled: true
    Spinbot:
      Enabled: true
      Spinbot#1:
        Enabled: true
    AutoSneak:
      Enabled: true
      AutoSneak#1:
        Enabled: true
    SkinBlinker:
      Enabled: true
      SkinBlinker#1:
        Enabled: true
